spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/security?useSSL=false&serverTimezone=UTC
        username: root
        password: 134596
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
# --- server
server:
  port: 8083



